name: Java CI with Maven

on:
  release:
    types:
      - created

jobs:
  ubuntu-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload JAR
      run: |
        mvn clean package
        ls target/
        mv target/wav-file-waveform-1.0-shaded.jar target/wav-file-waveform-ubuntu.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release Asset
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: target/wav-file-waveform-ubuntu.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  windows-build:
      runs-on: windows-latest
      steps:
        - name: Check out the code
          uses: actions/checkout@v2

        - name: Set up JDK 17
          uses: actions/setup-java@v2
          with:
            java-version: '17'
            distribution: 'temurin'

        - name: Build with Maven
          run: mvn -B package --file pom.xml

        - name: Upload JAR
          run: |
            mvn clean package
            ls target/
            mv target/wav-file-waveform-1.0-shaded.jar target/wav-file-waveform-windows.jar
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Create Release
          id: create_release_windows
          uses: softprops/action-gh-release@v1
          with:
            files: target/wav-file-waveform-windows.jar
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}